version: '3.8'

services:
  api:
    build: ./app
    container_name: julaw-api
    ports:
      - "3000:3000"
    #environment:
    #  - NODE_ENV=${NODE_ENV}
    #  - DB_HOST=${DB_HOST}
    #  - DB_USER=${DB_USER}
    #  - DB_PASSWORD=${DB_PASSWORD}
    #  - DB_NAME=${DB_NAME}
    volumes:
      - ./app:/app
    depends_on:
      - db
    networks:
      - julaw-api
      - julaw-ui
      - julaw-auth

  db:
    image: mysql:8.0
    container_name: julaw-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - julaw-api


networks:
  julaw-api:
  julaw-ui:
  julaw-auth:
    external: true