version: "3.8"

services:
  keycloak_db:
    image: postgres
    container_name: keycloak_db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    hostname: local
    restart: always
    volumes:
      - ./kc_volume:/var/lib/postgresql/data/
      - ./sql_volume:/docker-entrypoint-initdb.d/:ro
    ports: 
      - "5439:5432"
    networks:
      - kc_netwotk

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.4
    command: start-dev
    container_name: keycloak_app
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 500M
    memswap_limit: 2G
    environment:
      DB_VENDOR: ${DB_VENDOR}
      DB_ADDR: keycloak_db
      DB_PORT: 5432
      DB_SCHEMA: public
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_PROXY_MODE: edge
      KC_METRICS_ENABLED: true
      KC_HTTP_ENABLED: true
    ports:
      - "8089:8080"
      - "8443:8443"
    depends_on:
      - keycloak_db
    restart: always
    links: 
      - keycloak_db
    networks:
      - kc_netwotk
      - julaw-auth

networks:
  kc_netwotk:
    driver: bridge
  julaw-auth: 
    external: true